<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\DamageChargeResource\Pages; use App\Models\DamageCharge; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class DamageChargeResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = DamageCharge::class; protected static ?string $navigationIcon = 'heroicon-o-exclamation-triangle'; protected static ?string $navigationGroup = 'Stock'; protected static ?string $modelLabel = 'Dano/perda'; protected static ?string $pluralModelLabel = 'Danos e perdas';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Dano/perda')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\Select::make('reservation_id')->label('Reserva')->relationship('reservation','code'), Forms\Components\Select::make('room_id')->label('Quarto')->relationship('room','name'), Forms\Components\TextInput::make('description')->label('Descricao')->required(), Forms\Components\TextInput::make('amount')->label('Valor')->prefix('MZN')->numeric()->required(), Forms\Components\Select::make('status')->label('Estado')->options(['pending'=>'Pendente','charged'=>'Cobrado','waived'=>'Perdoado'])->required(), Forms\Components\FileUpload::make('photo_path')->label('Foto')->image()->directory('damage-charges')->visibility('public')->columnSpanFull(), Forms\Components\Textarea::make('notes')->label('Notas')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('created_at')->label('Data')->dateTime(), Tables\Columns\TextColumn::make('reservation.code')->label('Reserva'), Tables\Columns\TextColumn::make('description')->label('Descricao')->searchable(), Tables\Columns\TextColumn::make('amount')->label('Valor')->formatStateUsing(fn($state)=>number_format((float)$state,2).' MZN'), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListDamageCharges::route('/'),'create'=>Pages\CreateDamageCharge::route('/create'),'edit'=>Pages\EditDamageCharge::route('/{record}/edit')];}
}
