<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\FeedbackEntryResource\Pages; use App\Models\FeedbackEntry; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class FeedbackEntryResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = FeedbackEntry::class; protected static ?string $navigationIcon = 'heroicon-o-chat-bubble-left-right'; protected static ?string $navigationGroup = 'SaaS'; protected static ?string $modelLabel = 'Bug/opiniao'; protected static ?string $pluralModelLabel = 'Bugs e opinioes';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Feedback')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\Select::make('type')->label('Tipo')->options(['bug'=>'Bug','opinion'=>'Opiniao','request'=>'Pedido'])->required(), Forms\Components\TextInput::make('title')->label('Titulo')->required(), Forms\Components\Select::make('priority')->label('Prioridade')->options(['low'=>'Baixa','normal'=>'Normal','high'=>'Alta'])->required(), Forms\Components\Select::make('status')->label('Estado')->options(['open'=>'Aberto','planned'=>'Planeado','done'=>'Concluido'])->required(), Forms\Components\Textarea::make('description')->label('Descricao')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('created_at')->label('Data')->dateTime(), Tables\Columns\TextColumn::make('type')->label('Tipo')->badge(), Tables\Columns\TextColumn::make('title')->label('Titulo')->searchable(), Tables\Columns\TextColumn::make('priority')->label('Prioridade')->badge(), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListFeedbackEntries::route('/'),'create'=>Pages\CreateFeedbackEntry::route('/create'),'edit'=>Pages\EditFeedbackEntry::route('/{record}/edit')];}
}
