<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\KnowledgeGuideResource\Pages; use App\Models\KnowledgeGuide; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class KnowledgeGuideResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = KnowledgeGuide::class; protected static ?string $navigationIcon = 'heroicon-o-book-open'; protected static ?string $navigationGroup = 'Operação'; protected static ?string $modelLabel = 'Guia'; protected static ?string $pluralModelLabel = 'Guia operacional';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Guia')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\TextInput::make('category')->label('Categoria')->required(), Forms\Components\TextInput::make('title')->label('Titulo')->required(), Forms\Components\Select::make('status')->label('Estado')->options(['draft'=>'Rascunho','published'=>'Publicado'])->required(), Forms\Components\RichEditor::make('content')->label('Conteudo')->required()->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('category')->label('Categoria')->badge(), Tables\Columns\TextColumn::make('title')->label('Titulo')->searchable(), Tables\Columns\TextColumn::make('status')->label('Estado')->badge(), Tables\Columns\TextColumn::make('updated_at')->label('Atualizado')->dateTime()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListKnowledgeGuides::route('/'),'create'=>Pages\CreateKnowledgeGuide::route('/create'),'edit'=>Pages\EditKnowledgeGuide::route('/{record}/edit')];}
}
