<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\OperationalAlertResource\Pages; use App\Models\OperationalAlert; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class OperationalAlertResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = OperationalAlert::class; protected static ?string $navigationIcon = 'heroicon-o-bell-alert'; protected static ?string $navigationGroup = 'Operacional'; protected static ?string $modelLabel = 'Alerta'; protected static ?string $pluralModelLabel = 'Alertas operacionais';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Alerta')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\TextInput::make('source_type')->label('Origem técnica')->disabled()->dehydrated(false), Forms\Components\TextInput::make('source_id')->label('ID da origem')->disabled()->dehydrated(false), Forms\Components\Select::make('severity')->label('Severidade')->options(['info'=>'Info','warning'=>'Aviso','critical'=>'Crítico'])->required(), Forms\Components\TextInput::make('title')->label('Título')->required(), Forms\Components\Select::make('status')->label('Estado')->options(['open'=>'Aberto','resolved'=>'Resolvido'])->required(), Forms\Components\DateTimePicker::make('resolved_at')->label('Resolvido em'), Forms\Components\Textarea::make('message')->label('Mensagem')->columnSpanFull()])]); }
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('created_at')->label('Data')->dateTime()->sortable(), Tables\Columns\TextColumn::make('severity')->label('Severidade')->badge(), Tables\Columns\TextColumn::make('title')->label('Título')->searchable(), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]); }
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId)); }
    public static function getPages(): array { return ['index'=>Pages\ListOperationalAlerts::route('/'),'create'=>Pages\CreateOperationalAlert::route('/create'),'edit'=>Pages\EditOperationalAlert::route('/{record}/edit')]; }
}
