<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\OwnerDailyReportResource\Pages; use App\Models\OwnerDailyReport; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class OwnerDailyReportResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = OwnerDailyReport::class; protected static ?string $navigationIcon = 'heroicon-o-chart-bar-square'; protected static ?string $navigationGroup = 'Operacional'; protected static ?string $modelLabel = 'Relatorio diario'; protected static ?string $pluralModelLabel = 'Relatorios diarios do proprietario';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Relatorio diario')->columns(4)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\DatePicker::make('report_date')->label('Data')->default(now())->required(), Forms\Components\TextInput::make('revenue')->label('Receita')->prefix('MZN')->numeric(), Forms\Components\TextInput::make('expenses')->label('Despesas')->prefix('MZN')->numeric(), Forms\Components\TextInput::make('arrivals')->label('Entradas')->numeric(), Forms\Components\TextInput::make('departures')->label('Saidas')->numeric(), Forms\Components\TextInput::make('occupied_rooms')->label('Quartos ocupados')->numeric(), Forms\Components\TextInput::make('open_tasks')->label('Tarefas abertas')->numeric(), Forms\Components\TextInput::make('open_alerts')->label('Alertas abertos')->numeric(), Forms\Components\Select::make('status')->label('Estado')->options(['draft'=>'Rascunho','sent'=>'Enviado'])->required(), Forms\Components\Textarea::make('summary')->label('Resumo')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('report_date')->label('Data')->date()->sortable(), Tables\Columns\TextColumn::make('revenue')->label('Receita')->formatStateUsing(fn($state)=>number_format((float)$state,2).' MZN'), Tables\Columns\TextColumn::make('expenses')->label('Despesas')->formatStateUsing(fn($state)=>number_format((float)$state,2).' MZN'), Tables\Columns\TextColumn::make('occupied_rooms')->label('Ocupados'), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListOwnerDailyReports::route('/'),'create'=>Pages\CreateOwnerDailyReport::route('/create'),'edit'=>Pages\EditOwnerDailyReport::route('/{record}/edit')];}
}
