<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\RemoteApprovalResource\Pages; use App\Models\RemoteApproval; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class RemoteApprovalResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = RemoteApproval::class; protected static ?string $navigationIcon = 'heroicon-o-check-badge'; protected static ?string $navigationGroup = 'Operacional'; protected static ?string $modelLabel = 'Aprovacao remota'; protected static ?string $pluralModelLabel = 'Aprovacoes remotas';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Aprovacao')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\TextInput::make('type')->label('Tipo')->required(), Forms\Components\TextInput::make('subject')->label('Assunto')->required(), Forms\Components\TextInput::make('amount')->label('Valor')->prefix('MZN')->numeric(), Forms\Components\Select::make('status')->label('Estado')->options(['pending'=>'Pendente','approved'=>'Aprovado','rejected'=>'Rejeitado'])->required(), Forms\Components\DateTimePicker::make('decided_at')->label('Decidido em'), Forms\Components\Textarea::make('notes')->label('Notas')->columnSpanFull()])]); }
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('created_at')->label('Data')->dateTime()->sortable(), Tables\Columns\TextColumn::make('type')->label('Tipo')->badge(), Tables\Columns\TextColumn::make('subject')->label('Assunto')->searchable(), Tables\Columns\TextColumn::make('amount')->label('Valor')->formatStateUsing(fn($state)=>$state?number_format((float)$state,2).' MZN':'-'), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]); }
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId)); }
    public static function getPages(): array { return ['index'=>Pages\ListRemoteApprovals::route('/'),'create'=>Pages\CreateRemoteApproval::route('/create'),'edit'=>Pages\EditRemoteApproval::route('/{record}/edit')]; }
}
