<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\RoomInventoryResource\Pages; use App\Models\RoomInventory; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class RoomInventoryResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = RoomInventory::class; protected static ?string $navigationIcon = 'heroicon-o-clipboard-document-check'; protected static ?string $navigationGroup = 'Stock'; protected static ?string $modelLabel = 'Inventario de quarto'; protected static ?string $pluralModelLabel = 'Inventario por quarto';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Inventario')->columns(3)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\Select::make('room_id')->label('Quarto')->relationship('room','name')->required(), Forms\Components\TextInput::make('item_name')->label('Item')->required(), Forms\Components\TextInput::make('expected_quantity')->label('Qtd esperada')->numeric()->required(), Forms\Components\TextInput::make('current_quantity')->label('Qtd atual')->numeric()->required(), Forms\Components\TextInput::make('replacement_cost')->label('Custo reposicao')->prefix('MZN')->numeric(), Forms\Components\Select::make('status')->label('Estado')->options(['ok'=>'OK','missing'=>'Em falta','damaged'=>'Danificado'])->required(), Forms\Components\Textarea::make('notes')->label('Notas')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('room.name')->label('Quarto'), Tables\Columns\TextColumn::make('item_name')->label('Item')->searchable(), Tables\Columns\TextColumn::make('current_quantity')->label('Atual'), Tables\Columns\TextColumn::make('expected_quantity')->label('Esperado'), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListRoomInventories::route('/'),'create'=>Pages\CreateRoomInventory::route('/create'),'edit'=>Pages\EditRoomInventory::route('/{record}/edit')];}
}
