<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\StaffLeaveResource\Pages; use App\Models\StaffLeave; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class StaffLeaveResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = StaffLeave::class; protected static ?string $navigationIcon = 'heroicon-o-calendar'; protected static ?string $navigationGroup = 'Colaboradores'; protected static ?string $modelLabel = 'Ausencia/ferias'; protected static ?string $pluralModelLabel = 'Ausencias e ferias';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Ausencia')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\Select::make('staff_member_id')->label('Colaborador')->relationship('staffMember','name')->required(), Forms\Components\Select::make('type')->label('Tipo')->options(['vacation'=>'Ferias','sick'=>'Doenca','personal'=>'Pessoal','absence'=>'Ausencia'])->required(), Forms\Components\DatePicker::make('starts_at')->label('Inicio')->required(), Forms\Components\DatePicker::make('ends_at')->label('Fim')->required(), Forms\Components\Select::make('status')->label('Estado')->options(['requested'=>'Solicitado','approved'=>'Aprovado','rejected'=>'Rejeitado'])->required(), Forms\Components\Textarea::make('reason')->label('Motivo')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('staffMember.name')->label('Colaborador'), Tables\Columns\TextColumn::make('type')->label('Tipo')->badge(), Tables\Columns\TextColumn::make('starts_at')->label('Inicio')->date(), Tables\Columns\TextColumn::make('ends_at')->label('Fim')->date(), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListStaffLeaves::route('/'),'create'=>Pages\CreateStaffLeave::route('/create'),'edit'=>Pages\EditStaffLeave::route('/{record}/edit')];}
}
