<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\StaffAttendanceResource\Pages; use App\Models\StaffAttendance; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class StaffAttendanceResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = StaffAttendance::class; protected static ?string $navigationIcon = 'heroicon-o-clock'; protected static ?string $navigationGroup = 'Colaboradores'; protected static ?string $modelLabel = 'Presença'; protected static ?string $pluralModelLabel = 'Presenças';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Presença')->columns(2)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\Select::make('staff_member_id')->label('Colaborador')->relationship('staffMember','name')->required(), Forms\Components\DatePicker::make('attendance_date')->label('Data')->default(now())->required(), Forms\Components\DateTimePicker::make('checked_in_at')->label('Entrada'), Forms\Components\DateTimePicker::make('checked_out_at')->label('Saída'), Forms\Components\Select::make('status')->label('Estado')->options(['present'=>'Presente','late'=>'Atraso','absent'=>'Falta'])->required(), Forms\Components\FileUpload::make('checkin_photo_path')->label('Foto')->image()->directory('staff-attendance')->visibility('public')->columnSpanFull(), Forms\Components\Textarea::make('notes')->label('Notas')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('attendance_date')->label('Data')->date(), Tables\Columns\TextColumn::make('staffMember.name')->label('Colaborador'), Tables\Columns\TextColumn::make('checked_in_at')->label('Entrada')->dateTime(), Tables\Columns\TextColumn::make('checked_out_at')->label('Saída')->dateTime(), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListStaffAttendances::route('/'),'create'=>Pages\CreateStaffAttendance::route('/create'),'edit'=>Pages\EditStaffAttendance::route('/{record}/edit')];}
}
