<?php
namespace App\Filament\Resources;
use App\Filament\Concerns\HasResourcePermissions; use App\Filament\Resources\StockCountResource\Pages; use App\Models\StockCount; use App\Support\TenantContext; use Filament\Forms; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class StockCountResource extends Resource {
    use HasResourcePermissions; protected static ?string $model = StockCount::class; protected static ?string $navigationIcon = 'heroicon-o-calculator'; protected static ?string $navigationGroup = 'Stock'; protected static ?string $modelLabel = 'Contagem física'; protected static ?string $pluralModelLabel = 'Contagens físicas';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Section::make('Contagem')->columns(3)->schema([Forms\Components\Hidden::make('property_id')->default(fn()=>TenantContext::propertyId()), Forms\Components\Select::make('stock_item_id')->label('Produto')->relationship('stockItem','name')->required(), Forms\Components\Select::make('staff_member_id')->label('Responsavel')->relationship('staffMember','name'), Forms\Components\DatePicker::make('count_date')->label('Data')->default(now())->required(), Forms\Components\TextInput::make('system_quantity')->label('Qtd sistema')->numeric(), Forms\Components\TextInput::make('counted_quantity')->label('Qtd contada')->numeric()->required(), Forms\Components\Select::make('status')->label('Estado')->options(['draft'=>'Rascunho','approved'=>'Aprovada','adjusted'=>'Ajustada'])->required(), Forms\Components\Textarea::make('notes')->label('Notas')->columnSpanFull()])]);}
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('count_date')->label('Data')->date(), Tables\Columns\TextColumn::make('stockItem.name')->label('Produto'), Tables\Columns\TextColumn::make('system_quantity')->label('Sistema'), Tables\Columns\TextColumn::make('counted_quantity')->label('Contado'), Tables\Columns\TextColumn::make('difference')->label('Diferenca'), Tables\Columns\TextColumn::make('status')->label('Estado')->badge()])->actions([Tables\Actions\EditAction::make()->label('Editar')]);}
    public static function getEloquentQuery(): \Illuminate\Database\Eloquent\Builder { return parent::getEloquentQuery()->when(TenantContext::propertyId(), fn($query,int $propertyId)=>$query->where('property_id',$propertyId));}
    public static function getPages(): array { return ['index'=>Pages\ListStockCounts::route('/'),'create'=>Pages\CreateStockCount::route('/create'),'edit'=>Pages\EditStockCount::route('/{record}/edit')];}
}
